### PR TITLE
Make Infernal Mobs less broken

### PR DESCRIPTION
**Pull request by wlhlm**
I have recently started GTNH and generally like it, but I've found dealing with Infernal Mobs a bit frustrating. Looking at the issue tracker I'm certainly not the only one with this experience, so here is my attempt at making this mod less broken.

## Setup

First challenge was to actually build the thing. It was harder than usual, because the original author had multiple mods in a single repository and used a single ForgeGradle installation for all combined. Here are the rough steps to be able to build InfernalMobs from Source (this is in a UNIX environment, but Windows should be similar):

```
git clone "https://github.com/GTNewHorizons/atomicstrykers-minecraft-mods.git"
wget "https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-src.zip"
mkdir forgegradle
unzip -d forgegradle forge-1.7.10-10.13.4.1558-1.7.10-src.zip
cd forgegradle
./gradlew setupDecompWorkspace
cd ../atomicstrykers-minecraft-mods/InfernalMobs
../../forgegradle/gradlew setupDecompWorkspace
../../forgegradle/gradlew build
```
The jar can then be found in `build/libs`

## Fixes and enhancements

First, I backported some fixes from upstream development on later Minecraft versions:
- German, Chinese translation
- Fix bug with Choke not getting removed
  - This should fix the issue reported in GTNewHorizons/NewHorizons#2176, but I wasn't able to reproduce the issue in the first place, so I can't verify
- Unify Ender and Ninja teleport
  - Mobs no longer teleport into walls
  - Problem also mentioned in GTNewHorizons/NewHorizons#2176

Then I fixed some other outstanding problems:
- various modifier aspects have been made configurable, check Config section below for a list of options.
- fix modifiers getting lost when leaving and re-entering world immediately
  - affected singleplayer
- make modifiers ignore neutral and/or creative players
  - should make the Nether more friendly early game
  - problem also mentioned in GTNewHorizons/NewHorizons#3229, and GTNewHorizons/NewHorizons#5232
  - more detailed info in the table below
- GTNewHorizons/NewHorizons#2033
  - poison duration is now configurable
- GTNewHorizons/NewHorizons#4946
 - invisible modifier is no longer permanent in the default configuration

In accordance with @Dream-Master's wishes, I've changed some modifiers to no longer apply on ranged attacks (see table below for details)

| MobModifier | generally works | ignores creative | respects neutral status | ignores ranged attacks |
|-------------|-----------------------------------------------------------|------------------|-------------------------|------------------------|
| 1UP | f | y | y | n/a |
| Alchemist | y | y | y (fixed) | n/a |
| Berserk | y | y | y | n/a |
| Blastoff | y | f | y (fixed) | n |
| Bulwark | y | y | y | n/a |
| Choke | y | y | y (fixed) | n |
| Cloaking | y | n (intentional) | y (fixed) | n/a |
| Darkness | y | n (intentional) | y | y |
| Ender | y | y | y | n/a |
| Exhaust | y | y | y | n |
| Fiery | y | y | y | y |
| Ghastly | y | y | y (fixed) | n/a |
| Gravity | y | f | y | n |
| Lifesteal | f | y | y | n/a |
| Ninja | f | y | y | n/a |
| Poisonous | y | n (intentional) | y | y |
| Quicksand | y | f | y (fixed) | n/a |
| Regen | f (still problematic, see GTNewHorizons/NewHorizons#5553) | y | y | n/a |
| Rust | y | y | y | n |
| Sapper | y | n (intentional) | y | n |
| Sprint | y | n (intentional) | y | n/a |
| Sticky | y | f | y | y |
| Storm | y | f | y (fixed) | n/a |
| Vengeance | y | y | y | n |
| Weakness | y | n (intentional) | y | n |
| Webber | y | f | y (fixed) | n/a |
| Wither | y | n (intentional) | y | y |

**y**: yes, working correctly; **n**: no, not working correctly; **f**: fixed; **n/a**: not applicable

## Open issues

- GTNewHorizons/NewHorizons#2324
  - Can't reproduce, but might be fixed&mdash;testing required
- Webber still works as before, meaning it can clog up mob farms
- GTNewHorizons/NewHorizons#3229
  - Infernal mobs spawn too frequently
    - configurable, default values not changed with this pull request
  - Infernal mobs are too strong
    - max damage is configurable, default values not changed with this pull request
- GTNewHorizons/NewHorizons#5553
 - weird interaction between Regen modifier and regen enhancements from other mods
  - regen/health modification involves some hack in the InfernalMobs codebase, so it's not surprising that there are weird edge cases
  - don't know how to spawn an infernal undying mob so I don't know how to reproduce the issue.

## Configuration

I have made various aspects of modifiers configurable to allow the mod to be easier integrated into modpacks. Here is a raw dump of the default config file including comments for each option:

```
# Configuration file

general {
    I:AntiMobFarmCheckInterval=30
    B:AntiMobfarmingEnabled=true
    B:"MM_1UP enabled"=true
    B:"MM_Alchemist enabled"=true
    B:"MM_Berserk enabled"=true
    B:"MM_Blastoff enabled"=true
    B:"MM_Bulwark enabled"=true
    B:"MM_Choke enabled"=true
    B:"MM_Cloaking enabled"=true
    B:"MM_Darkness enabled"=true
    B:"MM_Ender enabled"=true
    B:"MM_Exhaust enabled"=true
    B:"MM_Fiery enabled"=true
    B:"MM_Ghastly enabled"=true
    B:"MM_Gravity enabled"=true
    B:"MM_Lifesteal enabled"=true
    B:"MM_Ninja enabled"=true
    B:"MM_Poisonous enabled"=true
    B:"MM_Quicksand enabled"=true
    B:"MM_Regen enabled"=true
    B:"MM_Rust enabled"=true
    B:"MM_Sapper enabled"=true
    B:"MM_Sprint enabled"=true
    B:"MM_Sticky enabled"=true
    B:"MM_Storm enabled"=true
    B:"MM_Vengeance enabled"=true
    B:"MM_Weakness enabled"=true
    B:"MM_Webber enabled"=true
    B:"MM_Wither enabled"=true

    # List of DimensionIDs where InfernalMobs will NEVER spawn
    S:dimensionIDBlackList=

    # Disables the ingame Health and Name overlay
    B:disableGUIoverlay=false

    # List of equally likely to drop Items for Elites, seperated by commas, syntax: ID-meta-stackSize-stackSizeRandomizer, everything but ID is optional, see changelog
    S:droppedItemIDsElite=iron_shovel,iron_pickaxe,iron_axe,iron_sword,iron_hoe,chainmail_helmet,chainmail_chestplate,chainmail_leggings,chainmail_boots,iron_helmet,iron_chestplate,iron_leggings,iron_boots,cookie-0-6

    # List of equally likely to drop Items for Infernals, seperated by commas, syntax: ID-meta-stackSize-stackSizeRandomizer, everything but ID is optional, see changelog
    S:droppedItemIDsInfernal=diamond-0-3,diamond_sword,diamond_shovel,diamond_pickaxe,diamond_axe,diamond_hoe,chainmail_helmet,chainmail_chestplate,chainmail_leggings,chainmail_boots,diamond_helmet,diamond_chestplate,diamond_leggings,diamond_boots,ender_pearl,enchanted_book

    # List of equally likely to drop Items for Ultras, seperated by commas, syntax: ID-meta-stackSize-stackSizeRandomizer, everything but ID is optional, see changelog
    S:droppedItemIDsUltra=bow,iron_hoe,chainmail_helmet,chainmail_chestplate,chainmail_leggings,chainmail_boots,iron_helmet,iron_chestplate,iron_leggings,iron_boots,golden_helmet,golden_chestplate,golden_leggings,golden_boots,golden_apple,blaze_powder-0-3,enchanted_book

    # One in THIS many Mobs will become atleast rare
    I:eliteRarity=15

    # One in THIS many already ultra Mobs will become infernal
    I:infernoRarity=7

    # Maximum number of Modifiers an Elite mob will receive
    I:maxEliteModifiers=5

    # Maximum number of Modifiers an Inferno mob will receive
    I:maxInfernoModifiers=15

    # Maximum number of Modifiers an Ultra mob will receive
    I:maxUltraModifiers=10

    # Minimum number of Modifiers an Elite mob will receive
    I:minEliteModifiers=2

    # Minimum number of Modifiers an Inferno mob will receive
    I:minInfernoModifiers=8

    # Minimum number of Modifiers an Ultra mob will receive
    I:minUltraModifiers=5
    D:mobFarmDamageThreshold=150.0

    # Multiplier applied ontop of all of the modified Mobs health
    S:mobHealthFactor=1.0

    # One in THIS many already rare Mobs will become atleast ultra
    I:ultraRarity=7

    # Use Entity class names instead of ingame Entity names for the config
    B:useSimpleEntityClassnames=true
}


mm_1up {
    # Multiplies the mob maximum health when healing back up, cannot get past maximum mob health
    D:healAmountMultiplier=1.0
}


mm_alchemist {
    # Time between ability uses
    D:coolDownMillis=6000.0
}


mm_berserk {
    # Maximum amount of damage that a mob with Berserk can deal (0, or less than zero for unlimited berserk damage)
    D:berserkMaxDamage=0.0

    # Damage multiplier, limited by maxOneShotDamage
    D:damageMultiplier=2.0
}


mm_blastoff {
    # Time between ability uses
    D:coolDownMillis=15000.0
}


mm_bulwark {
    # Damage (taken) multiplier, only makes sense for values < 1.0
    D:damageMultiplier=0.5
}


mm_cloaking {
    # Time mob is cloaked
    D:cloakingDurationTicks=200.0

    # Time between ability uses
    D:coolDownMillis=12000.0
}


mm_darkness {
    # Time attacker is darkened
    D:darknessDurationTicks=120.0
}


mm_ender {
    # Time between ability uses
    D:coolDownMillis=15000.0

    # When a mob with Ender modifier gets hurt it teleports and reflects some of the damage originally dealt. This sets the maximum amount that can be inflicted (0, or less than zero for unlimited reflect damage)
    D:enderReflectMaxDamage=10.0

    # When a mob with Ender modifier gets hurt it teleports and reflects some of the damage originally dealt. This sets the multiplier for the reflected damage
    D:enderReflectMultiplier=0.75
}


mm_fiery {
    # Time attacker is set on fire
    D:fieryDurationSecs=3.0
}


mm_ghastly {
    # Time between ability uses
    D:coolDownMillis=6000.0
}


mm_gravity {
    # Time between ability uses
    D:coolDownMillis=5000.0
}


mm_lifesteal {
    # Multiplies damage dealt, result is added to mob health
    D:lifestealMultiplier=1.0
}


mm_ninja {
    # Time between ability uses
    D:coolDownMillis=15000.0

    # When a mob with Ninja modifier gets hurt it teleports to the attacker and reflects some of the damage originally dealt. This sets the maximum amount that can be inflicted (0, or less than zero for unlimited reflect damage)
    D:ninjaReflectMaxDamage=10.0

    # When a mob with Ninja modifier gets hurt it teleports to the attacker and reflects some of the damage originally dealt. This sets the multiplier for the reflected damage
    D:ninjaReflectMultiplier=0.75
}


mm_poisonous {
    # Time attacker is poisoned
    D:poisonDurationTicks=120.0
}


mm_regen {
    # Time between ability uses
    D:coolDownMillis=500.0
}


mm_rust {
    # Damage dealt to Item in hand of attacking entity
    I:itemDamage=4
}


mm_sapper {
    # Time attacker is hungering
    D:hungerDurationTicks=120.0
}


mm_sprint {
    # Time between ability uses
    D:coolDownMillis=5000.0
}


mm_sticky {
    # Time between ability uses
    D:coolDownMillis=15000.0
}


mm_storm {
    # Time between ability uses
    D:coolDownMillis=15000.0
}


mm_vengeance {
    # Maximum amount of damage that is reflected (0, or less than zero for unlimited vengeance damage)
    D:vengeanceMaxDamage=0.0

    # Multiplies damage received, result is subtracted from attacking entity's health
    D:vengeanceMultiplier=0.5
}


mm_weakness {
    # Time attacker is weakened
    D:weaknessDurationTicks=120.0
}


mm_webber {
    # Time between ability uses
    D:coolDownMillis=15000.0
}


mm_wither {
    # Time attacker is withered
    D:witherDurationTicks=120.0
}
```

- - -

@richardhendricks please take a look.

### CODE REVIEW

**Comment by wlhlm** [comment]
I would like for people to try out the changes. Here is a pre-built version: [~~InfernalMobs-1.6.6gtnh1.zip~~](https://github.com/GTNewHorizons/atomicstrykers-minecraft-mods/files/2604779/InfernalMobs-1.6.6gtnh1.zip)*(superseded)*. If you don't feel like using random binaries from strangers on the Internet, you can build it yourself, instructions are in the PR.

**Review by bartimaeusnek — APPROVED** [review]
Nicely done, but i'd suggest setting up a Logger instead of using the FML log

**Comment by wlhlm** [comment]
> Nicely done, but i'd suggest setting up a Logger instead of using the FML log

Thanks. I've chosen it, because it's used in other places in the mod. Does using FML log break anything, or is setting up a logger just the right™ thing to do? If it's the latter, I'd just leave it how it is now, since the code is lacking in a lot of more places than that and would require a major rewrite anyway.

**Comment by bartimaeusnek** [comment]
A Logger makes differentiate the output from multiple mods easier, it also looks nicer... and to replace it its just adding a logger variable and re-routing the log outputs

**Comment by Dream-Master** [comment]
@bartimaeusnek can we merge this and put it in dev pack ?

**Comment by wlhlm** [comment]
~~Force pushed an update to change the wither modifier no longer being applied when mob gets hurt.~~

**Comment by Dream-Master** [comment]
@richardhendricks can you review it ? Thanks

**Comment by wlhlm** [comment]
I've found myself playing GTNH again after a hiatus and started working on Infernal Mobs again to get more changes in for the planned [2.0.9 update ("mobs and weapons")](https://github.com/GTNewHorizons/NewHorizons/milestone/66).

Here are some of the changes that were added:

- add configuration options for minimum and maximum number of modifiers each level of infernal mob can receive
- add some more modifier-specific configuration options
- remove `maxOneShotDamage` option that was global for all modifiers in favor of modifier-specific configuration options for max damage
- make certain modifiers not apply on ranged attacks
 - this affects Darkness, Fiery, Poisonous, Sticky, Wither
 - modifiers that apply when the mob is attacked regardless of ranged or melee attacks: Blastoff, Choke, Exhaust, Gravity, Rust, Sapper, Vengeance, Weakness

The last point was suggested to me by @Dream-Master (more than a year ago now, oops :-)). This changes the dynamic of the mod slightly (slight buff to bows, etc.), but I thinks it's in the right direction.

I've updated the top post with some details and references to new issues in connection with Infernal Mobs that popped up in the main modpack repo since first posting this PR.

Here is an updated build: [InfernalMobs-1.6.6gtnh1.zip](https://github.com/GTNewHorizons/atomicstrykers-minecraft-mods/files/4252623/InfernalMobs-1.6.6gtnh1.zip)

I wish for more people to try out these changes since these touch quite a few line of code, but I haven't really received any feedback since posting this more than a year ago. Based on my own experience and reading various in issues and in other places, I feel like there quite a few problems and frustrations with the version of Infernal Mobs currently shipped in GTNH and this PR addresses this. It doesn't make Infernal Mobs easy, but fixes some buggy/surprising behavior.

**Comment by Dream-Master** [comment]
will pack in my dev pack

**Comment by wlhlm** [comment]
Awesome. Thank you! ❤️

**Pull request merged**
